version: '3.1'

services:
    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: uber_eats
          POSTGRES_PASSWORD: uber_eats
          POSTGRES_DB: uber_eats
        ports:
            - "5433:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: